#DB configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.196.166.234:3306/microservice
    username: mercenary
    password:
  jmx:
    enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  activemq:
    broker-url: tcp://121.196.166.234:61616
    user: system
    password:
    queue-name: active.queue
    pool:
      enabled: true
      max-connections: 5
#Logging
logging:
  level:
    com.example.hellospringboot: debug